### ISSUE TITLE
Updates pushed to Discord update channel during update process causes update process to fail

### ISSUE THREAD

**Issue by MaceYaFace** [SpecialKO/SKIF#21] opened 2023-09-04 09:19 UTC
If a new version of SpecialK is pushed to the Discord update channel just as the update process in SKIF has started, it'll fail to update, showing the corresponding dialogue. Clicking, "Try again", does not work at all, forcing you to cancel. Cancelling the installation and starting up SKIF again, it complains the service is, "missing files", likely removed as part of the incomplete update process. At that point though of course, updating to the just pushed version, when prompted, then resolves all outstanding issues.

**Comment by Aemony** [comment] 2023-09-04 09:25
"Try again" is typically only shown when a file is unable to removed by the installer. Do you remember which one that it prompted about?

And what version of SK was installed before the update? One of the recent ones that was released in the past week?

The installer starts a new instance of SKIF with a cmd line argument telling it to stop the service and exit, and I guess it's possible that there is a slight possibility that the check for updates mistakenly starts as well in those instances...

Could you upload `SKIF.log.bak` from your folder? Hopefully it was created when the installer ran...

**Comment by Aemony** [comment] 2023-09-04 09:45
Thanks, I believe I've been able to reproduce it. The issue is that the instance of SKIF that the installer runs when it uses `Stop Quit` doesn't actually terminate immediately but relies on a window message `WM_CLOSE` it posts to itself for later processing. This behavior means that all the other main features of the app, such as the updater, game library, etc all starts processing which can end up keeping the instance running for far longer than intended.

I'll have a fix for it in the next version.

**Comment by MaceYaFace** [comment] 2023-09-04 10:43
Sounds good! Thanks for looking into this.

**Comment by Aemony** [comment] 2023-09-04 17:29
This was solved in [#a1a97d4](https://github.com/SpecialKO/SKIF/commit/a1a97d42f113cd79e14ffb6a78ce18ab557a4bd8) which was pushed as part of SK v 23.9.4.1 (SKIF v 0.9.94) to the Discord update channel just now.

**Closed by Aemony** 2023-09-04 17:29 UTC
